#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-fill $SCRIPTPATH/down.jpg
fi

leftwm-command "UnloadTheme"

# Kill procs
pkill dunst
pkill picom
pkill compton
pkill polybar