#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# my specific start-up things
setxkbmap -layout us,cz -variant ,ucw -option grp:caps_switch,grp:switch
autorandr --change

# set the theme.toml config
echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

# Boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
    picom &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton &> /dev/null & 
fi

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale "$SCRIPTPATH/wallpaper.jpg"
fi

# Boot polybar based on the number of monitors found
pkill polybar &
index=0
monitor="$(polybar -m | grep +0+0 | sed s/:.*// | tac)"
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | \
while read -r width x y
do 
  barname="mainbar$index"
  monitor="$(polybar -m | awk -v i="$(( index + 1 ))" 'NR==i{print}' | sed s/:.*// | tr -d '\n')"
  monitor=$monitor width=$(( width - 30 )) polybar -c "$SCRIPTPATH"/polybar.config $barname &
  let index=index+1
done