#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# my specific start-up things
setxkbmap -layout us,cz -variant ,ucw -option grp:caps_switch,grp:switch &

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

# Boot dunst if it exists
if [ -x "$(command -v dunst)" ]; then
  dunst -config $HOME/.config/leftwm/themes/current/dunstrc &
fi

# Boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton &> /dev/null & 
fi

# restore background using nitrogen or set default
if [ -x "$(command -v nitrogen)" ]; then
  nitrogen --restore &
elif [ -x "$(command -v feh)" ]; then
  feh --bg-scale "$SCRIPTPATH/wallpaper.jpg" &
fi

# Boot polybar based on the number of monitors found
pkill polybar &
index=0
monitor="$(polybar -m | grep +0+0 | sed s/:.*// | tac)"
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do 
  barname="mainbar$index"
  monitor="$(polybar -m | awk -v i="$(( index + 1 ))" 'NR==i{print}' | sed s/:.*// | tr -d '\n')"
  monitor=$monitor width=$(( width - 0 )) polybar -c "$SCRIPTPATH"/polybar.config $barname &
  let index=index+1
done